FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential pkg-config libncurses5-dev meson

COPY . /repo
WORKDIR /repo
RUN meson build --prefix=/install
RUN ninja -C build install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
