FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less man
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential pkg-config libncurses5-dev meson

ADD . /repo
WORKDIR /repo
RUN meson build
RUN ninja -C build install
